USE [master]
GO

/****** Object:  Database [CIBDb]    Script Date: 2020/06/29 01:48:07 ******/
CREATE DATABASE [CIBDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CIBDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CIBDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CIBDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CIBDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CIBDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CIBDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CIBDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CIBDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CIBDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CIBDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [CIBDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CIBDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CIBDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CIBDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CIBDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CIBDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CIBDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CIBDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CIBDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CIBDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CIBDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CIBDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CIBDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CIBDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CIBDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CIBDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CIBDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CIBDb] SET RECOVERY FULL 
GO

ALTER DATABASE [CIBDb] SET  MULTI_USER 
GO

ALTER DATABASE [CIBDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CIBDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CIBDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CIBDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CIBDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CIBDb] SET QUERY_STORE = OFF
GO

USE [CIBDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CIBDb] SET  READ_WRITE 
GO

